# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Tables
version:      0.25
version_from: lib/Class/Tables.pm
installdirs:  site
requires:
    Carp:                          0
    DBD::mysql:                    0
    DBI:                           0
    Lingua::EN::Inflect:           0
    overload:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
